language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

cache:
  directories:
    - vendor

install: composer install

script: vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
