language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

cache:
  directories:
    - vendor

install: composer install

script:
  - vendor/bin/phpstan analyse --level 7 src
  - vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
